---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loco-react-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: loco-react-app
  template:
    metadata:
      labels:
        app: loco-react-app
    spec:
      imagePullSecrets:
      - name: myregistrykey
      containers:
      - name: loco-react-app
        image: anupam19/react-frontend:latest
        ports:
        - containerPort: 4173
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 1m
            memory: 32Mi
          limits:
            cpu: 3m
            memory: 64Mi

        
---        
apiVersion: v1
kind: Service
metadata:
  name: loco-react-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4173
  selector:
    app: loco-react-app