---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sei-react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sei-react-app
  template:
    metadata:
      labels:
        app: sei-react-app
    spec:
      imagePullSecrets:
      - name: myregistrykey  
      containers:
      - name: sei-react-app
        image: anupam19/react-frontend:latest
        ports:
        - containerPort: 5173
        
---        
apiVersion: v1
kind: Service
metadata:
  name: sei-react-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5173
  selector:
    app: sei-react-app