apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress-test
spec:
  containers:
  - name: stress
    image: polinux/stress
    resources:
      limits:
        cpu: "1800m"
    command:
    - stress
    - --cpu
    - "1"
    - --timeout
    - "600s"

